name: CreditDecisioningV1
description: ''
version: 0.0.6
author: sparklearner123@gmail.com
language: python
buildSystem: wheel
pipelines:
  pipelines/Cleanup:
    name: Cleanup
    description: For repeated usage, remove previously written data
    author: sparklearner123@gmail.com
    mode: batch
    language: python
    createdAt: '2023-01-18 04:04:53'
    datasets:
      inputs:
      - datasets/FICO_table_history
      outputs: []
    dependencies: {}
  pipelines/ImportDataOption:
    name: ImportDataOption
    description: ''
    author: sparklearner123@gmail.com
    mode: batch
    language: python
    createdAt: '2023-01-10 22:24:26'
    datasets:
      inputs:
      - datasets/BNPLjsonIngest
      - datasets/CustIncomeCSV
      - datasets/creditReportXMLingest
      outputs: []
    dependencies: {}
  pipelines/CreateMetricsII:
    name: CreateMetricsII
    description: ''
    author: sparklearner123@gmail.com
    mode: batch
    language: python
    createdAt: '2023-01-25 19:43:31'
    datasets:
      inputs:
      - datasets/BNPLjsonIngest
      - datasets/CustIncomeCSV
      - datasets/creditReportXMLingest
      outputs:
      - datasets/DTIlong
    dependencies: {}
  pipelines/CreateMetrics:
    name: CreateMetrics
    description: ''
    author: sparklearner123@gmail.com
    mode: batch
    language: python
    createdAt: '2022-12-16 19:19:58'
    datasets:
      inputs:
      - datasets/BNPLjsonIngest
      - datasets/CustIncomeCSV
      - datasets/FICO_table_history
      - datasets/creditReportXMLingest
      - datasets/customer_info_v1
      - datasets/loan_data
      outputs:
      - datasets/FICO_table_history
      - datasets/ReportMetrics
    dependencies: {}
datasets:
  datasets/CreditReportDTI:
    name: CreditReportDTI
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2023-01-25 21:52:28'
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: File
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2023-01-25 21:52:28'
  datasets/creditReportXMLingest:
    name: creditReportXMLingest
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2023-01-20 17:01:42'
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: File
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2023-01-20 17:01:42'
  datasets/Bureau_XML:
    name: Bureau_XML
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2023-01-18 20:54:36'
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: File
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2023-01-18 20:54:36'
  datasets/loan_data:
    name: loan_data
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2022-12-21 21:29:18'
    physicalDatasets:
      Photon:
        fabricId: 1045
        datasetType: File
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2022-12-21 21:29:18'
  datasets/CustIncomeCSV:
    name: CustIncomeCSV
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2023-01-19 22:08:24'
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: File
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2023-01-19 22:08:24'
  datasets/CreditReportXML:
    name: CreditReportXML
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2023-01-18 21:12:37'
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: File
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2023-01-18 21:12:37'
  datasets/BNPLjson:
    name: BNPLjson
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2023-01-18 21:14:55'
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: File
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2023-01-18 21:14:55'
  datasets/CreditXML:
    name: CreditXML
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2023-01-19 22:03:37'
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: File
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2023-01-19 22:03:38'
  datasets/LexisNexisJSON:
    name: LexisNexisJSON
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2023-01-19 22:05:12'
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: File
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2023-01-19 22:05:12'
  datasets/credit_report_and_tradelines_v2:
    name: credit_report_and_tradelines_v2
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2022-12-16 19:36:23'
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: File
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2022-12-16 19:36:23'
  datasets/reportDTI:
    name: reportDTI
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2023-01-23 23:21:08'
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: File
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2023-01-23 23:21:08'
  datasets/ReportMetrics:
    name: ReportMetrics
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2023-01-11 04:05:26'
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: File
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2023-01-11 04:05:26'
  datasets/DTIlong:
    name: DTIlong
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2023-01-25 22:26:24'
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: File
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2023-01-25 22:26:24'
  datasets/BNPL_LexisNexis_v1:
    name: BNPL_LexisNexis_v1
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2022-12-16 20:29:33'
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: File
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2022-12-16 20:29:33'
  datasets/FICO_table_history:
    name: FICO_table_history
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2023-01-11 16:07:03'
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: File
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2023-01-11 16:07:03'
  datasets/BNPLjsonIngest:
    name: BNPLjsonIngest
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2023-01-20 16:52:01'
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: File
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2023-01-20 16:52:01'
  datasets/CreditXMLingest:
    name: CreditXMLingest
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2023-01-20 16:37:53'
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: File
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2023-01-20 16:37:53'
  datasets/ReportDebtIncome:
    name: ReportDebtIncome
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2023-01-25 22:12:55'
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: File
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2023-01-25 22:12:55'
  datasets/customer_info_v1:
    name: customer_info_v1
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2022-12-16 20:24:38'
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: File
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2022-12-16 20:24:38'
templates: {}
jobs:
  jobs/DTIjob:
    name: DTIjob
    description: CalculatesDebtToIncomeRatio
    fabricUID: 990
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0 1/1 * ? *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/CreateMetrics
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: true
    createdAt: '2023-01-18 02:30:06'
    author: sparklearner123@gmail.com
libraries: []
subgraphs:
  subgraphs/BNPL_API:
    name: BNPL_API
    description: ''
    author: sparklearner123@gmail.com
    language: python
    createdAt: '2023-01-18 01:53:19'
  subgraphs/CreateDTIMetrics:
    name: CreateDTIMetrics
    description: ''
    author: sparklearner123@gmail.com
    language: python
    createdAt: '2023-01-11 16:35:29'
  subgraphs/CalculateDebtAndIncome:
    name: CalculateDebtAndIncome
    description: ''
    author: sparklearner123@gmail.com
    language: python
    createdAt: '2023-01-11 03:28:24'
  subgraphs/TestAuditPrepGraph:
    name: TestAuditPrepGraph
    description: ''
    author: sparklearner123@gmail.com
    language: python
    createdAt: '2023-01-19 18:53:13'
  subgraphs/PrepDTI:
    name: PrepDTI
    description: 'A standard pattern we use for parsing and unioning data from TransUnion,
      LexisNexis, and self-reported credit. '
    author: sparklearner123@gmail.com
    language: python
    createdAt: '2023-01-19 00:59:26'
sqlModels: {}
sqlPipeline: null
dependencies: []
projectDependencies: {}
pipelineConfigurations: {}
